import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react'
import styles from '../styles/Home.module.css'

export default function Home() {
  const [number, setNumber] = useState(true)
  // useEffect(()=>{
  //   setInterval(() => {
  //     setNumber(true)
  //   }, 1000 * 60);
  // },[]);
  useEffect(()=>{
    if(number){
      setTimeout(() => {
        setNumber(false)
      }, 1000 * 60 * parseInt(Math.random()*10));
    }
    if(!number){
      setTimeout(()=>{
        setNumber(true)
      },1000 * 10)
    }
  },[number])
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={"App"}>
        {number && <iframe src='https://jagan.pro' alt="https://jagan.pro" />}
      </main>
    </div>
  )
}
